HOST: http://localhost:3003

# token of 'root' user

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODQyYzIzNWQ1MmQ3NDY2YWFlM2UxOSIsInVzZXJuYW1lIjoicm9vdCIsImlhdCI6MTYwMjUzMDkxM30.FdI1wJ76muxngyJiIgYgMbRBExN72bRE893VHzkXVIE

# token of 'roota' user

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODU3OWI1YjJlMzRiNjRiZWE5YjA3ZiIsInVzZXJuYW1lIjoicm9vdGEiLCJpYXQiOjE2MDI1ODMxMTl9.KBf0S6-5-GG7cQGqmi2pbWo2O6E_PmaCTtDcSFk2pEQ

GET /api/blogs

# post blog after authorization

POST /api/blogs
{
  "title": "Rad blog",
  "author": "Jonathan",
  "url": "www.com",
  "likes": 13
}

# invalid blog
POST /api/blogs
{
  "author": "Jonathan",
  "url": "www.com",
  "likes": 13
}

# post fails midway, created only w/ _id, __v fields
# due to invalid json - trailing comma
POST /api/blogs
{
  "title": "Rad blog",
  "author": "Jonathan",
}

GET /api/blogs/

DELETE /api/blogs/5f84b845f60bad30a30caf1a

# following lacks 'user' field in blog
DELETE /api/blogs/5f842c3955383446aee6bd5d

# 'root' trying to delete blog of 'roota'
DELETE /api/blogs/5f857c22b2e34b64bea9b080

GET /api/blogs

PUT /api/blogs/5f7857157eb03871f8adf170
{
    "author": "Bob Blogger",
    "id": "5f7857157eb03871f8adf170",
    "likes": 5,
    "title": "First blog ti",
    "url": "https://bobo"
}


GET /api/blogs

PUT /api/blogs/5f7991fc65e9b79148876f18
{
    "_id": "5f7857157eb03871f8adf170",
    "id": "0000",
    "INVALKEY": "0000"
}

# users api

GET /api/users

POST /api/users
{
  "username": "root",
  "password": "rootpass",
  "name": "Root User"
}

POST /api/users
{
  "username": "roota",
  "password": "rootapass",
  "name": "Roota User"
}

# login api

POST /api/login
{
  "username": "root",
  "password": "rootpass"
}

POST /api/login
{
  "username": "roota",
  "password": "rootapass"
}

