# http://localhost:3001
# --
Host: http://localhost:3001


# $host = http://localhost:3001


# --
# GET $host/api/notes/ 

GET /api/notes/ 

GET /api/notes/5f71dccfaa7975798aa8f046 

PUT /api/notes/5f7cd0f6b347aca793bb73a8
{
    "content": "Note of a user updated"
}

DELETE /api/notes/4

DELETE $host/api/notes/4

POST /api/notes
{
	"content": "Easy note",
	"important": "true"
}

POST /api/unknownx
{
	"content": "Note posted via vial",
	"important": "true"
}

POST /api/users
{
    "username": "roota2",
    "password": "pass",
    "name": "Bob"
}

GET /api/users

POST /api/notes
{
    "content": "Note of a user",
    "userId": "5f7cc6d904509cdfabd6952f"
}

POST /api/notes
{
}

# login

POST /api/login
{
    "username": "roota2",
    "password": "pass"
}

# authorization for post note

# user: roota2: "id": "5f7cc7fee2b400e3645451b2",
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhMiIsImlkIjoiNWY3Y2M3ZmVlMmI0MDBlMzY0NTQ1MWIyIiwiaWF0IjoxNjAyMjM5MDk3fQ.eVg3kDv43pqQ5h9O-cfUnP33m5p2Nru-7NkWMkzNymI


POST /api/notes
{
    "content": "Note of a user"
}

